name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t api99/docker-react -f ./Dockerfile.dev .
      - run: docker run -e CI=true api99/docker-react npm test


#      - run: docker build -t api99/multi-client-10-14 ./client
#      - run: docker build -t api99/multi-nginx-10-14 ./nginx
#      - run: docker build -t api99/multi-server-10-14 ./server
#      - run: docker build -t api99/multi-worker-10-14 ./worker
#
      - run: docker push api99/docker-react

#      - run: docker push api99/multi-client-10-14
#      - run: docker push api99/multi-nginx-10-14
#      - run: docker push api99/multi-server-10-14
#      - run: docker push api99/multi-worker-10-14

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: api99/docker-react
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-react
          environment_name: Docker-react-env
          existing_bucket_name: elasticbeanstalk-eu-central-1-729632440439
          region: us-central-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip